# Generated by Django 3.2.17 on 2023-02-19 08:36

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataInput',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('input_c1', models.FileField(blank=True, null=True, upload_to=main.models.upload_to)),
                ('input_b1', models.FileField(blank=True, null=True, upload_to=main.models.upload_to)),
                ('input_m1', models.FileField(blank=True, null=True, upload_to=main.models.upload_to)),
                ('featured_df', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=500)),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
    ]
