# Generated by Django 3.2.17 on 2023-02-22 11:55

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_pict', models.ImageField(upload_to=main.models.upload_to)),
            ],
        ),
    ]
