# Generated by Django 3.2.17 on 2023-02-09 08:38

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_inputdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataInput',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data', models.FileField(blank=True, null=True, upload_to=main.models.upload_to)),
            ],
        ),
        migrations.DeleteModel(
            name='InputData',
        ),
    ]
