# Generated by Django 3.2.17 on 2023-02-14 14:44

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20230209_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='datainput',
            name='featured_dataframe',
            field=models.FileField(blank=True, null=True, upload_to=main.models.upload_to),
        ),
        migrations.AddField(
            model_name='datainput',
            name='input_b1',
            field=models.FileField(blank=True, null=True, upload_to=main.models.upload_to),
        ),
        migrations.AddField(
            model_name='datainput',
            name='input_c1',
            field=models.FileField(blank=True, null=True, upload_to=main.models.upload_to),
        ),
        migrations.AddField(
            model_name='datainput',
            name='input_m1',
            field=models.FileField(blank=True, null=True, upload_to=main.models.upload_to),
        ),
    ]
