# Generated by Django 3.2.17 on 2023-02-14 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20230214_2144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datainput',
            name='data',
        ),
    ]
